Update index.html
Zunnurayni/Collaboration pull request #8
Opened 2020-05-18 13:31 UTC by Adamumujtaba

Upload my name (Mujtaba Adamu)

2020-05-18 16:08 UTC, Zunnurayni requested changes
make it the 8 list tag

2020-05-18 20:16 UTC, Adamumujtaba reviewed
I change the position

2020-05-18 20:17 UTC, Adamumujtaba commented
I change the position successfully

2020-05-19 15:18 UTC, Zunnurayni approved these changes

2020-05-19 15:19 UTC, closed without merging